-- DropForeignKey
ALTER TABLE "partyLes" DROP CONSTRAINT "partyLes_TR_fkey";

-- AlterTable
ALTER TABLE "TR" ALTER COLUMN "TRID" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "partyLes" ALTER COLUMN "TR" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "partyLes" ADD CONSTRAINT "partyLes_TR_fkey" FOREIGN KEY ("TR") REFERENCES "TR"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
